### PR TITLE
Add compatibility with AndroidX

### PR DESCRIPTION
**Pull request by loic-lopez**

### CODE REVIEW

**Comment by loic-lopez** [comment]
It seems that the Example directory is not building because of `react-native-gesture-handler` version is too low in order to support AndroidX

**Comment by xuwilliam** [comment]
@loic-lopez Looks like to get this to pass Travis, react-native-gesture-handler in the Example folder's package.json needs to be updated to at least 1.4.0. Unfortunately the version of react-native-gesture-handler that supports AndroidX is also locked into RN .60 whereas the Example project is still on RN .59.3

https://github.com/kmagiera/react-native-reanimated/blob/master/Example/package.json

**Comment by loic-lopez** [comment]
@xuwilliam I think, I will migrate also the example folder to  RN .60.

**Comment by dulmandakh** [comment]
Sorry, couldn't wait and create a duplicate, but CI passing PR https://github.com/kmagiera/react-native-reanimated/pull/395

**Comment by kmagiera** [comment]
Thanks for submitting this PR, as I've just merged #395 which covers the migration I'm going to close this one. Thank you for your contribution regardless 🙌

**Pull request closed without merging**
