### PR TITLE
[web] Added shim for web

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

Prevents crashing when referenced in libs like react-navigation.

### CODE REVIEW

**Comment by ken0x0a** [comment]
I'm happier if it "works as expected" than "warning", so I hope .web.js with functionality will added to react-navigation.

**Comment by EvanBacon** [comment]
@ken0x0a it's better to incrementally add functionality, as opposed to building an entire feature and hoping the author agrees with your approach.

**Comment by EvanBacon** [comment]
IMO it's better to incrementally add functionality, as opposed to building an entire feature and hoping the author agrees with your approach. If _you_ would like to make it "work as expected", please [press here](https://github.com/kmagiera/react-native-reanimated/pulls/new).

**Comment by EvanBacon** [comment]
Related https://github.com/kmagiera/react-native-gesture-handler/pull/555

**Pull request merged**
