### PR TITLE
Remove deprecated componentWillMount

### PR DESCRIPTION
**Pull request by owinter86**
Refactors the create animated component removing the deprecated componentWillMount lifecycle and moving the attachProps to the constructor.

### CODE REVIEW

**Comment by osdnk** [comment]
can't we move to `UNSAFE`. That what we've done in RN core.

**Comment by owinter86** [comment]
Why would we need to do it for this usage of CWM, given we have access to props in the constructor?

**Comment by osdnk** [comment]
let's say:
```
const a = <Animated.View ...>
```
is invoked outside render. It will trigger constructor, but not CWM / CDM. In this case we don't want to attach props, no?

**Comment by owinter86** [comment]
Im not sure I fully understand, sorry. I understand that declaring that constant wont trigger the constructor, but how would you invoke this outside a render and then use it inside a render so different props appear in the constructor and CWM.

**Comment by osdnk** [comment]
```
render() {
  return (
    {this.state.visible ? A : null}
  )
}
```

**Comment by owinter86** [comment]
Doesn't the constructor and CWM get called when state is visible both with the same props?

**Comment by osdnk** [comment]
I think so. Let you check! Maybe I'm wrong :)

**Comment by owinter86** [comment]
From what I understand, the only time the constructor and CWM are called are when this.A is returned in the render method, triggering the constructor and CWM method with the same prop values.

I am not sure how you can invoke `A = <Animated.View ...>` outside a render method, and then reuse the same instance inside a render method, invoking the lifecycle methods with new props?

The example above will call the constructor and CWM only when visible is true, and neither get called when false as this.A is never invoked.

**Comment by ScreamZ** [comment]
Which release ?

**Comment by suretarget** [comment]
@ScreamZ in master branch.
`yarn add https://github.com/kmagiera/react-native-reanimated.git\#master`

**Comment by ScreamZ** [comment]
That's good but I don't like to rely on master using NPM, It's better to fix version :D

**Comment by avasuro** [comment]
Strange thing, according to commits history PR with this fix should have been released in current version (v1.2.0), but if I used this version from npm - error is still appears, and if I look at source code in node_modules - this fix is not presented there.

**Comment by ScreamZ** [comment]
@FrederickEngelhardt So ?

**Comment by mattmogford** [comment]
This doesn't seem to be in 1.2.0 ...?

**Comment by anastely** [comment]
I have v1.2.0 and the issue is still!

**Comment by sincraianul** [comment]
@kmagiera Please release a patch version (1.2.0) on NPM that includes this fix.

**Comment by rmindo** [comment]
This should be in NPM already.

**Comment by IntelliJAbhishek** [comment]
@rmindo its not there

**Comment by net8floz** [comment]
would love a npm fix!

**Comment by chrisparton1991** [comment]
This is fixed in v1.3.0, which is available on NPM. I was still getting the warning after upgrading, but clearing the transform cache fixed that:
```
npm start -- --reset-cache
```

**Comment by mattmogford** [comment]
v1.3.0
```yarn cache clean```
for yarn users

**Comment by kmagiera** [comment]
Sorry for responding here so late but just noticed this change when browsing through the codebase.

We should *not* be calling `_attachProps` in the constructor as this may lead to memory leaks. Attaching props allocates resources on the native side that are then released by `ropsAnimated.__detach()` which is called in `componentWillUnmount`. React does not guarantee that the constructor call leads to the component being mounted. So if it does not get mounted we will never release resources as unmounting won't happen as well.

Instead of doing that this call should've been moved to `componentDidMount` and not into the class constructor.

**Pull request merged**
