### PR TITLE
fix(🐛): Add TS support for animated transforms

### PR DESCRIPTION
**Pull request by wcandillon**
🎉Finally, we can type View transformations 😍

### CODE REVIEW

**Comment by wcandillon** [comment]
🙌🏻I use https://www.npmjs.com/package/patch-package to run patched version of the typing on older reanimated releases and it works like a charm.

**Comment by tpucci** [comment]
Hi 👋 @wcandillon I have trouble using this commit. It seems that `TransformStyle` is not defined.

**Comment by tpucci** [comment]
I fixed it here: https://github.com/kmagiera/react-native-reanimated/pull/339

**Comment by wcandillon** [comment]
@tpucci yes thks 🙌🏻

**Pull request merged**
