### PR TITLE
Update react-native-reanimated.d.ts

### PR DESCRIPTION
**Pull request by iamolegga**
Hi, just opened this example:
https://github.com/kmagiera/react-native-reanimated/blob/master/Example/imageViewer/index.js
tried to translate it to TS, and found small issue with type declarations

Now for example it should allow to pass array of arrays to `cond` if/else arguments

### CODE REVIEW

**Comment by osdnk** [comment]
Thanks!

**Comment by ckknight** [comment]
This is leading to breakages as `Adaptable` is now self-referential, which is a violation of the type system.

**Comment by ckknight** [comment]
This is leading to breakages as `Adaptable` is now self-referential, which is a violation of the type system. CC @osdnk

**Comment by iamolegga** [comment]
@ckknight any example? In my case it works just fine now

**Comment by ckknight** [comment]
Any usage with TypeScript 3.3.4000 gives an error in that `Animated` is not a generic type, as it stems from the initial error of `Animated` being self-referential.

**Comment by ckknight** [comment]
```
node_modules/react-native-reanimated/react-native-reanimated.d.ts:58:17 - error TS2456: Type alias 'Adaptable' circularly references itself.

58     export type Adaptable<T> =
                   ~~~~~~~~~
```

**Comment by iamolegga** [comment]
Sorry for that,
fixed it in #243

**Pull request merged**
