### PR TITLE
fix build on android

### PR DESCRIPTION
**Pull request by Krosh**
This commit fix error "Could not resolve all artifacts for configuration ':react-native-reanimated:classpath'". I just up grade version and add google repo

### CODE REVIEW

**Comment by osdnk** [comment]
Hi, @Krosh 
Is it actually needed? Isn't it possible even to drop `com.android.tools.build:gradle:3.1.4` and `repositories` from project, because you actually provide them with your root project, don't you? Take a look here https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/build.gradle 
If you update your app to newer RN's version it might require more changes which are not related to library. `https://github.com/kmagiera/react-native-gesture-handler/pull/377`

**Comment by Krosh** [comment]
To be honest, I didn't know that it's possible. I saw how another library fix this issues and made same fix. Ofc your solution is better

**Comment by osdnk** [comment]
Could you confirm it works?

**Comment by Krosh** [comment]
@osdnk yes, I'm successfully built project with forked react-native-reanimated

**Comment by osdnk** [comment]
noce, thanks

**Comment by SaeedZhiany** [comment]
@osdnk and @Krosh 

Have you tested to open the android project of this library as a stand-alone project? AFAIK it will not be built in such cases.

**Comment by SaeedZhiany** [comment]
@friederbluemle 

can you take a look at this, please?

**Comment by friederbluemle** [comment]
Hey @SaeedZhiany - Good catch, and thanks for the heads up!

Opened a PR here, please check: #463

**Comment by SaeedZhiany** [comment]
@friederbluemle 

It seems @osdnk and @Krosh took the idea from https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/build.gradle
I think it's also needed to submit such a PR in that repository.

**Comment by friederbluemle** [comment]
Yes, that's true, `react-native-gesture-handler` needs similar (though a few more) fixes - I have a local branch already, but it needs additional testing. It's a little more complicated than in this repo here.

**Comment by friederbluemle** [comment]
I already opened a PR with some preliminary cleanups about 2 weeks ago: https://github.com/kmagiera/react-native-gesture-handler/pull/817 - Once that's in, I will proceed with the next step. It's easier to review in small targeted changesets.

**Comment by SaeedZhiany** [comment]
I was going to create a PR like your on that, so I leave it to you.

Thanks

**Pull request merged**
