### PR TITLE
Add backward compatible API typings

### PR DESCRIPTION
**Pull request by osdnk**
Issue related: https://github.com/kmagiera/react-native-reanimated/issues/138

### CODE REVIEW

**Comment by henrikra** [comment]
Looks good to me 👍

**Comment by henrikra** [comment]
Only thing I would change is `backwardCompatibleWrapper` => `BackwardCompatibleWrapper`. After that merge and publish?

**Comment by osdnk** [comment]
nice, thanks @henrikra 
ping @kmagiera

**Comment by kmagiera** [comment]
Thanks @henrikra for the review. And thanks @osdnk for this PR. Merging in

**Pull request merged**
