### PR TITLE
Renamed ViewStyleProps to DeprecatedViewStyleProps.

### PR DESCRIPTION
**Pull request by msand**
https://github.com/facebook/react-native/pull/21415
https://github.com/facebook/react-native/issues/21342

### CODE REVIEW

**Comment by osdnk** [comment]
Thanks!

**Comment by osdnk** [comment]
@msand 
But AFAIK now we drop support for any RN version before this commit facebook/react-native#21415. If yes, it's not a good solution 😢

**Comment by msand** [comment]
Maybe better remove the code that uses it, it's merely a warning anyway.

**Comment by msand** [comment]
Or, keep a separate list of keys in an array, instead of importing this.

**Pull request merged**
